<?php

return [
    'pokja_groups' => [
        'AKP' => 'MEDIS',
        'PAB' => 'MEDIS',
        'HPK' => 'MEDIS',
        'KE' => 'MEDIS',
        'PAP' => 'MEDIS',
        'PKPO' => 'MEDIS',
        'PP' => 'MEDIS',
        'SKP' => 'MEDIS',
        'KPS' => 'MANAJEMEN',
        'MFK' => 'MANAJEMEN',
        'MRMIK' => 'MANAJEMEN',
        'PMKP' => 'MANAJEMEN',
        'PPI' => 'MANAJEMEN',
        'PPK' => 'MANAJEMEN',
        'PROGNAS' => 'MANAJEMEN',
        'TKRS' => 'MANAJEMEN',
    ],

    'drive_structures' => [
        'AKP' => [
            '1' => 4,
            '1.1' => 3,
            '1.2' => 4,
            '1.3' => 2,
            '2' => 4,
            '2.1' => 4,
            '3' => 6,
            '3.1' => 3,
            '4' => 2,
            '5' => 4,
            '5.1' => 3,
            '5.2' => 5,
            '5.3' => 3,
            '5.4' => 4,
            '5.5' => 5,
            '5.6' => 4,
            '5.7' => 3,
            '6' => 2,
        ],
        'PAB' => [
            '1' => 3,
            '2' => 3,
            '3' => 3,
            '3.1' => 3,
            '3.2' => 3,
            '4' => 3,
            '5' => 2,
            '6' => 2,
            '6.1' => 3,
            '7' => 2,
            '7.1' => 2,
            '7.2' => 2,
            '7.3' => 3,
            '7.4' => 4,
        ],
        'HPK' => [
            '1' => 4,
            '1.1' => 3,
            '1.2' => 3,
            '1.3' => 4,
            '1.4' => 2,
            '1.5' => 3,
            '2' => 5,
            '2.1' => 2,
            '2.2' => 2,
            '3' => 3,
            '4' => 3,
            '4.1' => 3,
            '4.2' => 2,
        ],
        'KE' => [
            '1' => 4,
            '2' => 4,
            '3' => 3,
            '4' => 3,
            '5' => 5,
            '6' => 4,
            '7' => 2,
        ],
        'PAP' => [
            '1' => 2,
            '1.1' => 5,
            '1.2' => 5,
            '2' => 3,
            '2.1' => 4,
            '2.2' => 4,
            '2.3' => 3,
            '2.4' => 6,
            '2.5' => 2,
            '2.6' => 4,
            '2.7' => 3,
            '3' => 5,
            '4' => 4,
            '5' => 2,
        ],
        'PKPO' => [
            '1' => 4,
            '2' => 5,
            '3' => 4,
            '3.1' => 5,
            '3.2' => 2,
            '3.3' => 4,
            '4' => 2,
            '4.1' => 5,
            '5' => 7,
            '5.1' => 2,
            '6' => 4,
            '6.1' => 3,
            '7' => 2,
            '7.1' => 2,
        ],
        'PP' => [
            '1' => 4,
            '1.1' => 6,
            '1.2' => 4,
            '1.3' => 2,
            '2' => 4,
            '3' => 2,
            '3.1' => 2,
            '3.2' => 2,
            '3.3' => 4,
            '3.4' => 2,
            '3.5' => 2,
            '3.6' => 2,
            '3.7' => 2,
            '3.8' => 2,
            '3.9' => 4,
            '4' => 2,
            '4.1' => 2,
            '4.2' => 2,
            '4.3' => 4,
            '4.4' => 2,
            '4.5' => 2,
        ],
        'SKP' => [
            '1' => 4,
            '2' => 3,
            '3' => 3,
            '3.1' => 3,
            '4' => 4,
            '5' => 2,
            '6' => 2,
            '6.1' => 3,
        ],
        'KPS' => [
            '1' => 6,
            '2' => 2,
            '3' => 2,
            '4' => 3,
            '5' => 3,
            '6' => 2,
            '7' => 4,
            '8' => 4,
            '8.1' => 3,
            '9' => 7,
            '10' => 6,
            '10.1' => 3,
            '11' => 5,
            '12' => 7,
            '13' => 3,
            '14' => 5,
            '15' => 2,
            '16' => 4,
            '17' => 4,
            '18' => 2,
            '19' => 4,
        ],
        'MFK' => [
            '1' => 3,
            '2' => 4,
            '3' => 4,
            '4' => 4,
            '5' => 5,
            '5.1' => 3,
            '6' => 6,
            '7' => 6,
            '8' => 2,
            '8.1' => 5,
            '8.2' => 5,
            '8.2.1' => 4,
            '8.3' => 3,
            '9' => 6,
            '10' => 4,
            '11' => 4,
        ],
        'MRMIK' => [
            '1' => 5,
            '2' => 2,
            '2.1' => 3,
            '2.2' => 3,
            '3' => 3,
            '4' => 2,
            '5' => 4,
            '6' => 3,
            '7' => 2,
            '8' => 4,
            '9' => 2,
            '10' => 3,
            '11' => 3,
            '12' => 4,
            '13' => 5,
            '13.1' => 3,
        ],
        'PMKP' => [
            '1' => 4,
            '2' => 3,
            '3' => 2,
            '4' => 7,
            '4.1' => 3,
            '5' => 2,
            '6' => 4,
            '7' => 3,
            '8' => 5,
            '9' => 3,
            '10' => 2,
            '11' => 6,
        ],
        'PPI' => [
            '1' => 4,
            '1.1' => 2,
            '2' => 2,
            '3' => 2,
            '4' => 5,
            '4.1' => 3,
            '5' => 3,
            '6' => 3,
            '7' => 4,
            '7.1' => 3,
            '7.2' => 5,
            '8' => 3,
            '9' => 3,
            '10' => 4,
            '10.1' => 3,
            '11' => 3,
            '11.1' => 4,
            '12' => 3,
            '13' => 3,
        ],
        'PPK' => [
            '1' => 4,
            '2' => 3,
            '3' => 3,
            '4' => 3,
            '5' => 4,
            '6' => 6,
        ],
        'PROGNAS' => [
            '1' => 5,
            '1.1' => 3,
            '2' => 4,
            '2.1' => 3,
            '2.2' => 4,
            '3' => 6,
            '4' => 3,
            '4.1' => 2,
            '5' => 4,
            '5.1' => 3,
            '6' => 5,
            '6.1' => 1,
        ],
        'TKRS' => [
            '1' => 4,
            '2' => 3,
            '3' => 4,
            '3.1' => 3,
            '4' => 4,
            '5' => 3,
            '6' => 6,
            '7' => 6,
            '7.1' => 4,
            '8' => 3,
            '9' => 5,
            '10' => 4,
            '11' => 3,
            '12' => 4,
            '13' => 6,
            '14' => 2,
            '15' => 4,
        ],
    ],

    'document_requirements' => [
        'PPK 1 / EP 1' => ['count' => 1, 'evidence' => '[R] Perjanjian kerja sama dengan institusi penyelenggara pendidikan kesehatan yang masih berlaku.'],
        'PPK 1 / EP 2' => ['count' => 2, 'evidence' => '[D] 1. Daftar institusi pendidikan yang bekerja sama dengan rumah sakit; 2. Sertifikat akreditasi institusi pendidikan.'],
        'PPK 1 / EP 3' => ['count' => 2, 'evidence' => '[R] Pernyataan dalam perjanjian kerja sama yang mencantumkan kriteria penerimaan peserta didik; [D] Daftar peserta didik per periode.'],
        'PPK 1 / EP 4' => ['count' => 1, 'evidence' => '[D] Kajian terhadap hasil evaluasi program pendidikan kesehatan sekurang-kurangnya satu kali setahun.'],
        'PPK 2 / EP 1' => ['count' => 1, 'evidence' => 'Penetapan pengelolaan dan pengawasan pelaksanaan pendidikan klinis yang meliputi poin a-c pada maksud dan tujuan.'],
        'PPK 2 / EP 2' => ['count' => 1, 'evidence' => '[D] Daftar lengkap seluruh peserta pendidikan klinis yang saat ini berada di rumah sakit.'],
        'PPK 2 / EP 3' => ['count' => 1, 'evidence' => '[D] Kelengkapan dokumen peserta pendidikan klinis yang meliputi poin a-e pada maksud dan tujuan.'],
        'PPK 3 / EP 1' => ['count' => 1, 'evidence' => '[D] Perhitungan rasio pendidik klinis dan peserta didik per periode.'],
        'PPK 3 / EP 2' => ['count' => 2, 'evidence' => '1. Perhitungan peserta didik dan data rata-rata jumlah pasien per periode; 2. Bukti pertemuan institusi pendidikan dengan rumah sakit mengenai perhitungan tersebut.'],
        'PPK 3 / EP 3' => ['count' => 1, 'evidence' => '[D] Daftar inventaris sarana prasarana, teknologi dan informasi, serta perpustakaan atau e-library.'],
        'PPK 4 / EP 1' => ['count' => 2, 'evidence' => '1. Penetapan staf klinis sebagai pendidik klinis; 2. Penetapan kewenangan memberikan pendidikan klinis dalam SPK dan RKK.'],
        'PPK 4 / EP 2' => ['count' => 1, 'evidence' => '[D] Daftar staf klinis pemberi pendidikan klinis beserta seluruh gelar akademis dan profesinya.'],
        'PPK 4 / EP 3' => ['count' => 2, 'evidence' => '1. Sertifikat pelatihan pendidik klinis; 2. Sertifikat keprofesian berkelanjutan.'],
        'PPK 5 / EP 1' => ['count' => 1, 'evidence' => 'Penetapan tingkat supervisi setiap peserta pendidikan klinis untuk setiap jenjang pendidikan.'],
        'PPK 5 / EP 2' => ['count' => 3, 'evidence' => '[D] 1. Surat level kompetensi dari institusi pendidikan; 2. Bukti tanda pengenal level kompetensi; 3. Bukti log book peserta didik.'],
        'PPK 5 / EP 3' => ['count' => 1, 'evidence' => '[D] Bukti log book peserta didik dan dokumentasi proses supervisi.'],
        'PPK 5 / EP 4' => ['count' => 1, 'evidence' => 'Bukti pengkajian rekam medis untuk memastikan kewenangan pengisian dan supervisi oleh DPJP.'],
        'PPK 6 / EP 1' => ['count' => 1, 'evidence' => 'Penetapan Komite/Tim Koordinasi Pendidikan atau unit pengelola pendidikan klinis beserta uraian tugas dan tanggung jawab.'],
        'PPK 6 / EP 2' => ['count' => 1, 'evidence' => 'Program orientasi bagi peserta pendidikan klinis.'],
        'PPK 6 / EP 3' => ['count' => 1, 'evidence' => '[D] Bukti pelaksanaan orientasi peserta pendidikan klinis.'],
        'PPK 6 / EP 4' => ['count' => 1, 'evidence' => '[D] Bukti keikutsertaan peserta didik dalam program peningkatan mutu dan keselamatan pasien.'],
        'PPK 6 / EP 5' => ['count' => 1, 'evidence' => 'Monitoring, evaluasi, dan analisis dampak peserta didik terhadap mutu dan keselamatan pasien sekurang-kurangnya setahun sekali.'],
        'PPK 6 / EP 6' => ['count' => 1, 'evidence' => '[D] Hasil survei kepuasan pasien sekurang-kurangnya setahun sekali.'],

        'SKP 1 / EP 1' => ['count' => 1, 'evidence' => '[R] Penetapan sasaran keselamatan pasien meliputi poin 1-6 pada gambaran umum.'],
        'SKP 1 / EP 2' => ['count' => 0, 'evidence' => 'Tidak ada dokumen D/R; bukti penilaian berupa observasi, wawancara, dan/atau simulasi.'],
        'SKP 1 / EP 3' => ['count' => 0, 'evidence' => 'Tidak ada dokumen D/R; bukti penilaian berupa observasi, wawancara, dan/atau simulasi.'],
        'SKP 1 / EP 4' => ['count' => 1, 'evidence' => '[D] Bukti identifikasi pasien pada situasi khusus dan penggunaan label.'],
        'SKP 2 / EP 1' => ['count' => 1, 'evidence' => '[D] Bukti rekam medis komunikasi instruksi melalui telepon dan pelaporan kepada DPJP.'],
        'SKP 2 / EP 2' => ['count' => 2, 'evidence' => '[R] Penetapan hasil kritis pemeriksaan penunjang diagnostik; [D] Bukti rekam medis pelaporan hasil kritis.'],
        'SKP 2 / EP 3' => ['count' => 1, 'evidence' => '[D] Bukti rekam medis serah terima.'],
        'SKP 3 / EP 1' => ['count' => 1, 'evidence' => '[R] Penetapan daftar obat kewaspadaan tinggi termasuk LASA/NORUM.'],
        'SKP 3 / EP 2' => ['count' => 0, 'evidence' => 'Tidak ada dokumen D/R; bukti penilaian berupa observasi dan wawancara.'],
        'SKP 3 / EP 3' => ['count' => 1, 'evidence' => '[D] Bukti evaluasi dan pembaruan daftar obat High-Alert dan LASA/NORUM setahun sekali.'],
        'SKP 3.1 / EP 1' => ['count' => 1, 'evidence' => '[R] Penetapan daftar elektrolit konsentrat yang dapat disimpan di luar instalasi farmasi.'],
        'SKP 3.1 / EP 2' => ['count' => 0, 'evidence' => 'Tidak ada dokumen D/R; bukti penilaian berupa observasi dan wawancara.'],
        'SKP 3.1 / EP 3' => ['count' => 2, 'evidence' => '[R] Penetapan protokol koreksi hipokalemia, hiponatremia, dan hipofosfatemia; [D] Bukti penerapan protokol.'],
        'SKP 4 / EP 1' => ['count' => 1, 'evidence' => '[D] Bukti pelaksanaan verifikasi praoperasi dengan daftar tilik.'],
        'SKP 4 / EP 2' => ['count' => 1, 'evidence' => '[R] Penetapan tanda penandaan sisi operasi/tindakan invasif yang seragam, mudah dikenali, dan tidak bermakna ganda.'],
        'SKP 4 / EP 3' => ['count' => 1, 'evidence' => '[D] Bukti rekam medis site marking.'],
        'SKP 4 / EP 4' => ['count' => 1, 'evidence' => '[D] Bukti rekam medis Time-Out menggunakan Surgical Safety Checklist WHO terkini.'],
        'SKP 5 / EP 1' => ['count' => 0, 'evidence' => 'Tidak ada dokumen D/R; bukti penilaian berupa observasi, wawancara, dan simulasi.'],
        'SKP 5 / EP 2' => ['count' => 1, 'evidence' => '[D] Bukti evaluasi dan upaya perbaikan program kebersihan tangan.'],
        'SKP 6 / EP 1' => ['count' => 1, 'evidence' => '[D] Bukti rekam medis skrining risiko jatuh rawat jalan.'],
        'SKP 6 / EP 2' => ['count' => 1, 'evidence' => '[D] Bukti tindakan/intervensi mengurangi risiko jatuh rawat jalan.'],
        'SKP 6.1 / EP 1' => ['count' => 1, 'evidence' => '[D] Bukti rekam medis pengkajian risiko jatuh rawat inap.'],
        'SKP 6.1 / EP 2' => ['count' => 1, 'evidence' => '[D] Bukti rekam medis pengkajian ulang risiko jatuh.'],
        'SKP 6.1 / EP 3' => ['count' => 1, 'evidence' => '[D] Bukti rekam medis tindakan/intervensi mengurangi risiko jatuh rawat inap.'],

        'PMKP 1 / EP 1' => ['count' => 1, 'evidence' => '[R] Penetapan Pedoman PMKP serta manajemen risiko.'],
        'PMKP 1 / EP 2' => ['count' => 3, 'evidence' => '[R] 1. Penetapan Komite/Tim Mutu RS; 2. Pedoman kerja; 3. Program kerja Komite/Tim Mutu RS.'],
        'PMKP 1 / EP 3' => ['count' => 1, 'evidence' => '[R] Penetapan program PMKP RS oleh Direktur dan pengesahan representatif pemilik/dewan pengawas.'],
        'PMKP 1 / EP 4' => ['count' => 1, 'evidence' => '[D] Bukti evaluasi program PMKP dalam rapat koordinasi triwulan.'],
        'PMKP 2 / EP 1' => ['count' => 1, 'evidence' => '[D] Bukti rapat pemilihan indikator mutu prioritas.'],
        'PMKP 2 / EP 2' => ['count' => 2, 'evidence' => '[D] 1. Bukti rapat koordinasi dan integrasi pengukuran; 2. Bukti supervisi ke unit layanan.'],
        'PMKP 2 / EP 3' => ['count' => 2, 'evidence' => '[D] 1. Bukti integrasi laporan insiden dan pengukuran budaya keselamatan; 2. Bukti solusi/perbaikan terintegrasi.'],
        'PMKP 3 / EP 1' => ['count' => 1, 'evidence' => '[D] Bukti pengumpulan data INM, IMP-RS, dan IMP-Unit.'],
        'PMKP 3 / EP 2' => ['count' => 1, 'evidence' => '[R] Profil indikator IMP-RS dan IMP-Unit mencakup poin a-t.'],
        'PMKP 4 / EP 1' => ['count' => 1, 'evidence' => '[D] Bukti agregasi dan analisis seluruh indikator mutu.'],
        'PMKP 4 / EP 2' => ['count' => 1, 'evidence' => '[D] Laporan triwulan hasil analisis yang memuat rekomendasi tindakan perbaikan dan efisiensi penggunaan sumber daya.'],
        'PMKP 4 / EP 3' => ['count' => 1, 'evidence' => '[D] Bukti laporan triwulan kepada Direktur dan representatif pemilik/dewan pengawas.'],
        'PMKP 4 / EP 4' => ['count' => 2, 'evidence' => '[D] 1. Bukti e-report INM ke Kementerian Kesehatan; 2. Bukti e-report IKP ke KNKP.'],
        'PMKP 4 / EP 5' => ['count' => 1, 'evidence' => '[D] Bukti pelaksanaan pembelajaran menggunakan database eksternal untuk perbandingan internal, RS setara, praktik terbaik, dan sumber ilmiah profesional.'],
        'PMKP 4 / EP 6' => ['count' => 1, 'evidence' => '[D] Bukti keamanan dan kerahasiaan pelaporan database eksternal.'],
        'PMKP 4 / EP 7' => ['count' => 1, 'evidence' => '[D] Bukti analisis efisiensi biaya dan sumber daya pada proyek prioritas.'],
        'PMKP 4.1 / EP 1' => ['count' => 1, 'evidence' => '[D] Bukti pengumpulan dan analisis data menjadi informasi perbaikan.'],
        'PMKP 4.1 / EP 2' => ['count' => 1, 'evidence' => '[D] Sertifikat pelatihan PMKP staf pengukuran.'],
        'PMKP 4.1 / EP 3' => ['count' => 1, 'evidence' => '[D] Bukti pelaporan hasil analisis kepada penanggung jawab indikator.'],
        'PMKP 5 / EP 1' => ['count' => 1, 'evidence' => '[D] Bukti validasi data sesuai poin a-f.'],
        'PMKP 5 / EP 2' => ['count' => 1, 'evidence' => '[D] Bukti validasi data yang dipublikasikan.'],
        'PMKP 6 / EP 1' => ['count' => 4, 'evidence' => '[D] 1. Rencana perbaikan; 2. Uji coba skala kecil; 3. Analisis hasil uji coba; 4. Penerapan luas.'],
        'PMKP 6 / EP 2' => ['count' => 6, 'evidence' => '[D] 1. Pengumpulan data; 2. Validasi; 3. Analisis; 4. Rencana perbaikan; 5. Implementasi; 6. Bukti perbaikan berkelanjutan.'],
        'PMKP 6 / EP 3' => ['count' => 1, 'evidence' => '[D] Bukti perubahan regulasi/proses untuk mempertahankan perbaikan.'],
        'PMKP 6 / EP 4' => ['count' => 1, 'evidence' => '[D] Bukti keberhasilan dalam laporan triwulan.'],
        'PMKP 7 / EP 1' => ['count' => 2, 'evidence' => '[D] 1. Bukti evaluasi clinical pathway; 2. Clinical pathway berbasis PPK.'],
        'PMKP 7 / EP 2' => ['count' => 1, 'evidence' => '[D] Bukti capaian kepatuhan DPJP dan pengurangan variasi clinical pathway.'],
        'PMKP 7 / EP 3' => ['count' => 1, 'evidence' => '[D] Bukti audit klinis/medis pada prioritas standar pelayanan kedokteran.'],
        'PMKP 8 / EP 1' => ['count' => 1, 'evidence' => '[R] Pedoman Sistem Pelaporan dan Pembelajaran Keselamatan Pasien Rumah Sakit.'],
        'PMKP 8 / EP 2' => ['count' => 1, 'evidence' => '[R] Penetapan tim investigator ad hoc untuk investigasi komprehensif/RCA kejadian sentinel.'],
        'PMKP 8 / EP 3' => ['count' => 1, 'evidence' => '[D] Bukti tindakan korektif dan pemantauan efektivitas hasil RCA.'],
        'PMKP 8 / EP 4' => ['count' => 1, 'evidence' => '[R] Ketentuan investigasi sederhana sesuai grading dalam Pedoman SP2KP.'],
        'PMKP 8 / EP 5' => ['count' => 1, 'evidence' => '[D] Bukti tindakan korektif dan pemantauan hasil investigasi sederhana.'],
        'PMKP 9 / EP 1' => ['count' => 3, 'evidence' => '[D] 1. Pengumpulan data insiden; 2. Analisis insiden; 3. Pelaporan insiden.'],
        'PMKP 9 / EP 2' => ['count' => 1, 'evidence' => '[D] Bukti RCA/simple RCA ketika terjadi tingkat, pola, atau tren tak diharapkan.'],
        'PMKP 9 / EP 3' => ['count' => 1, 'evidence' => '[D] Laporan triwulan outcome insiden keselamatan pasien.'],
        'PMKP 10 / EP 1' => ['count' => 1, 'evidence' => '[D] Hasil survei dan evaluasi budaya keselamatan pasien tahunan.'],
        'PMKP 10 / EP 2' => ['count' => 1, 'evidence' => '[R] Penetapan program budaya keselamatan pasien berdasarkan hasil survei.'],
        'PMKP 11 / EP 1' => ['count' => 1, 'evidence' => '[D] Bukti supervisi penerapan program manajemen risiko.'],
        'PMKP 11 / EP 2' => ['count' => 1, 'evidence' => '[D] Daftar risiko rumah sakit berdasarkan daftar risiko unit.'],
        'PMKP 11 / EP 3' => ['count' => 1, 'evidence' => '[D] Profil risiko dan rencana penanganan.'],
        'PMKP 11 / EP 4' => ['count' => 3, 'evidence' => '[D] 1. Ceklis pemantauan; 2. Hasil pemantauan; 3. Laporan hasil pemantauan enam bulanan.'],
        'PMKP 11 / EP 5' => ['count' => 1, 'evidence' => '[R] Penetapan Program Manajemen Risiko Rumah Sakit oleh Direktur.'],
        'PMKP 11 / EP 6' => ['count' => 1, 'evidence' => '[D] Bukti FMEA proses berisiko tinggi setahun sekali.'],
    ],
];
