<?php

$expandDocumentRequirements = static function (array $profiles): array {
    $requirements = [];

    foreach ($profiles as $pokja => $standards) {
        foreach ($standards as $standard => $counts) {
            foreach ($counts as $index => $count) {
                $element = $index + 1;
                $evidence = $count === 0
                    ? 'Tidak ada dokumen D/R pada kolom Kelengkapan Bukti; penilaian menggunakan observasi, wawancara, dan/atau simulasi.'
                    : sprintf(
                        '[D/R] %d butir dokumen sesuai kolom Kelengkapan Bukti instrumen akreditasi 2024.',
                        $count,
                    );

                $requirements["{$pokja} {$standard} / EP {$element}"] = [
                    'count' => $count,
                    'evidence' => $evidence,
                ];
            }
        }
    }

    return $requirements;
};

return [
    'pokja_groups' => [
        'AKP' => 'MEDIS',
        'PAB' => 'MEDIS',
        'HPK' => 'MEDIS',
        'KE' => 'MEDIS',
        'PAP' => 'MEDIS',
        'PKPO' => 'MEDIS',
        'PP' => 'MEDIS',
        'SKP' => 'MEDIS',
        'KPS' => 'MANAJEMEN',
        'MFK' => 'MANAJEMEN',
        'MRMIK' => 'MANAJEMEN',
        'PMKP' => 'MANAJEMEN',
        'PPI' => 'MANAJEMEN',
        'PPK' => 'MANAJEMEN',
        'PROGNAS' => 'MANAJEMEN',
        'TKRS' => 'MANAJEMEN',
    ],

    'drive_structures' => [
        'AKP' => [
            '1' => 4,
            '1.1' => 3,
            '1.2' => 4,
            '1.3' => 2,
            '2' => 4,
            '2.1' => 4,
            '3' => 6,
            '3.1' => 3,
            '4' => 2,
            '5' => 4,
            '5.1' => 3,
            '5.2' => 5,
            '5.3' => 3,
            '5.4' => 4,
            '5.5' => 5,
            '5.6' => 4,
            '5.7' => 3,
            '6' => 4,
        ],
        'PAB' => [
            '1' => 3,
            '2' => 3,
            '3' => 3,
            '3.1' => 3,
            '3.2' => 3,
            '4' => 3,
            '5' => 2,
            '6' => 2,
            '6.1' => 3,
            '7' => 2,
            '7.1' => 2,
            '7.2' => 2,
            '7.3' => 3,
            '7.4' => 4,
        ],
        'HPK' => [
            '1' => 4,
            '1.1' => 3,
            '1.2' => 3,
            '1.3' => 4,
            '1.4' => 2,
            '1.5' => 3,
            '2' => 5,
            '2.1' => 2,
            '2.2' => 2,
            '3' => 3,
            '4' => 3,
            '4.1' => 3,
            '4.2' => 2,
        ],
        'KE' => [
            '1' => 4,
            '2' => 4,
            '3' => 3,
            '4' => 3,
            '5' => 5,
            '6' => 4,
            '7' => 2,
        ],
        'PAP' => [
            '1' => 2,
            '1.1' => 5,
            '1.2' => 5,
            '2' => 3,
            '2.1' => 4,
            '2.2' => 4,
            '2.3' => 3,
            '2.4' => 6,
            '2.5' => 2,
            '2.6' => 4,
            '2.7' => 3,
            '3' => 5,
            '4' => 4,
            '5' => 2,
        ],
        'PKPO' => [
            '1' => 4,
            '2' => 5,
            '3' => 4,
            '3.1' => 5,
            '3.2' => 2,
            '3.3' => 4,
            '4' => 2,
            '4.1' => 5,
            '5' => 7,
            '5.1' => 2,
            '6' => 4,
            '6.1' => 3,
            '7' => 2,
            '7.1' => 3,
        ],
        'PP' => [
            '1' => 4,
            '1.1' => 6,
            '1.2' => 4,
            '1.3' => 2,
            '2' => 4,
            '3' => 2,
            '3.1' => 2,
            '3.2' => 2,
            '3.3' => 4,
            '3.4' => 2,
            '3.5' => 2,
            '3.6' => 2,
            '3.7' => 2,
            '3.8' => 2,
            '3.9' => 4,
            '4' => 2,
            '4.1' => 2,
            '4.2' => 2,
            '4.3' => 4,
            '4.4' => 2,
            '4.5' => 2,
        ],
        'SKP' => [
            '1' => 4,
            '2' => 3,
            '3' => 3,
            '3.1' => 3,
            '4' => 4,
            '5' => 2,
            '6' => 2,
            '6.1' => 3,
        ],
        'KPS' => [
            '1' => 6,
            '2' => 2,
            '3' => 2,
            '4' => 3,
            '5' => 3,
            '6' => 2,
            '7' => 4,
            '8' => 4,
            '8.1' => 3,
            '9' => 7,
            '10' => 6,
            '10.1' => 3,
            '11' => 5,
            '12' => 7,
            '13' => 3,
            '14' => 5,
            '15' => 2,
            '16' => 4,
            '17' => 4,
            '18' => 2,
            '19' => 4,
        ],
        'MFK' => [
            '1' => 3,
            '2' => 4,
            '3' => 4,
            '4' => 4,
            '5' => 5,
            '5.1' => 3,
            '6' => 6,
            '7' => 6,
            '8' => 2,
            '8.1' => 5,
            '8.2' => 5,
            '8.2.1' => 4,
            '8.3' => 3,
            '9' => 6,
            '10' => 4,
            '11' => 8,
        ],
        'MRMIK' => [
            '1' => 5,
            '2' => 2,
            '2.1' => 3,
            '2.2' => 3,
            '3' => 3,
            '4' => 2,
            '5' => 4,
            '6' => 3,
            '7' => 2,
            '8' => 4,
            '9' => 2,
            '10' => 3,
            '11' => 3,
            '12' => 4,
            '13' => 5,
            '13.1' => 3,
        ],
        'PMKP' => [
            '1' => 4,
            '2' => 3,
            '3' => 2,
            '4' => 7,
            '4.1' => 3,
            '5' => 2,
            '6' => 4,
            '7' => 3,
            '8' => 5,
            '9' => 3,
            '10' => 2,
            '11' => 6,
        ],
        'PPI' => [
            '1' => 4,
            '1.1' => 2,
            '2' => 2,
            '3' => 2,
            '4' => 5,
            '4.1' => 3,
            '5' => 3,
            '6' => 3,
            '7' => 4,
            '7.1' => 3,
            '7.2' => 5,
            '8' => 3,
            '9' => 3,
            '10' => 4,
            '10.1' => 3,
            '11' => 3,
            '11.1' => 4,
            '12' => 3,
            '13' => 3,
        ],
        'PPK' => [
            '1' => 4,
            '2' => 3,
            '3' => 3,
            '4' => 3,
            '5' => 4,
            '6' => 6,
        ],
        'PROGNAS' => [
            '1' => 5,
            '1.1' => 3,
            '2' => 4,
            '2.1' => 3,
            '2.2' => 4,
            '3' => 6,
            '4' => 3,
            '4.1' => 2,
            '5' => 4,
            '5.1' => 3,
            '6' => 5,
            '6.1' => 4,
        ],
        'TKRS' => [
            '1' => 4,
            '2' => 3,
            '3' => 4,
            '3.1' => 3,
            '4' => 4,
            '5' => 3,
            '6' => 6,
            '7' => 6,
            '7.1' => 4,
            '8' => 3,
            '9' => 5,
            '10' => 4,
            '11' => 3,
            '12' => 4,
            '13' => 6,
            '14' => 2,
            '15' => 7,
        ],
    ],

    'document_requirements' => [
        ...$expandDocumentRequirements([
            'PAB' => [
                '1' => [2, 2, 1],
                '2' => [1, 2, 1],
                '3' => [1, 1, 2],
                '3.1' => [2, 1, 1],
                '3.2' => [1, 1, 2],
                '4' => [1, 1, 1],
                '5' => [1, 1],
                '6' => [1, 1],
                '6.1' => [1, 1, 1],
                '7' => [1, 1],
                '7.1' => [1, 1],
                '7.2' => [1, 2],
                '7.3' => [1, 1, 1],
                '7.4' => [1, 1, 1, 1],
            ],
            'PAP' => [
                '1' => [1, 2],
                '1.1' => [1, 1, 1, 1, 1],
                '1.2' => [1, 1, 1, 1, 1],
                '2' => [1, 2, 1],
                '2.1' => [1, 2, 1, 1],
                '2.2' => [1, 2, 2, 1],
                '2.3' => [1, 2, 1],
                '2.4' => [1, 1, 3, 1, 2, 2],
                '2.5' => [1, 1],
                '2.6' => [2, 3, 0, 2],
                '2.7' => [1, 2, 2],
                '3' => [3, 3, 1, 1, 1],
                '4' => [1, 1, 1, 1],
                '5' => [1, 2],
            ],
            'PKPO' => [
                '1' => [2, 2, 1, 1],
                '2' => [2, 1, 1, 1, 1],
                '3' => [0, 1, 1, 0],
                '3.1' => [0, 0, 0, 0, 0],
                '3.2' => [0, 1],
                '3.3' => [1, 1, 1, 1],
                '4' => [1, 1],
                '4.1' => [1, 1, 1, 1, 1],
                '5' => [1, 1, 2, 2, 1, 0, 0],
                '5.1' => [2, 1],
                '6' => [3, 0, 1, 1],
                '6.1' => [1, 1, 1],
                '7' => [1, 2],
                '7.1' => [1, 1, 1],
            ],
            'PP' => [
                '1' => [1, 1, 2, 1],
                '1.1' => [1, 1, 1, 1, 1, 1],
                '1.2' => [2, 1, 1, 3],
                '1.3' => [1, 1],
                '2' => [1, 1, 1, 1],
                '3' => [1, 3],
                '3.1' => [2, 1],
                '3.2' => [2, 1],
                '3.3' => [2, 2, 2, 2],
                '3.4' => [1, 2],
                '3.5' => [1, 1],
                '3.6' => [2, 1],
                '3.7' => [1, 1],
                '3.8' => [1, 1],
                '3.9' => [2, 2, 1, 1],
                '4' => [2, 3],
                '4.1' => [2, 1],
                '4.2' => [2, 1],
                '4.3' => [1, 2, 2, 2],
                '4.4' => [1, 1],
                '4.5' => [1, 1],
            ],
            'AKP' => [
                '1' => [1, 1, 2, 2],
                '1.1' => [2, 1, 1],
                '1.2' => [1, 1, 1, 2],
                '1.3' => [1, 1],
                '2' => [1, 2, 2, 1],
                '2.1' => [1, 1, 2, 1],
                '3' => [1, 1, 0, 1, 2, 1],
                '3.1' => [2, 1, 1],
                '4' => [1, 1],
                '5' => [1, 1, 1, 1],
                '5.1' => [1, 2, 1],
                '5.2' => [5, 1, 1, 1, 1],
                '5.3' => [1, 1, 1],
                '5.4' => [1, 1, 2, 2],
                '5.5' => [1, 2, 1, 2, 1],
                '5.6' => [1, 1, 1, 2],
                '5.7' => [1, 1, 1],
                '6' => [1, 1, 3, 2],
            ],
            'HPK' => [
                '1' => [2, 1, 1, 1],
                '1.1' => [2, 1, 1],
                '1.2' => [0, 1, 3],
                '1.3' => [1, 1, 1, 1],
                '1.4' => [1, 1],
                '1.5' => [2, 1, 1],
                '2' => [1, 1, 1, 1, 1],
                '2.1' => [2, 1],
                '2.2' => [1, 1],
                '3' => [1, 2, 1],
                '4' => [2, 1, 1],
                '4.1' => [1, 1, 1],
                '4.2' => [1, 1],
            ],
            'KE' => [
                '1' => [1, 1, 2, 1],
                '2' => [1, 1, 1, 1],
                '3' => [1, 1, 1],
                '4' => [1, 1, 7],
                '5' => [1, 1, 1, 1, 1],
                '6' => [1, 1, 1, 1],
                '7' => [1, 1],
            ],
            'PPI' => [
                '1' => [1, 1, 1, 1],
                '1.1' => [1, 1],
                '2' => [1, 1],
                '3' => [2, 1],
                '4' => [1, 2, 1, 1, 2],
                '4.1' => [1, 1, 1],
                '5' => [1, 1, 1],
                '6' => [1, 1, 1],
                '7' => [1, 2, 2, 4],
                '7.1' => [1, 0, 1],
                '7.2' => [0, 4, 1, 3, 1],
                '8' => [1, 1, 1],
                '9' => [0, 1, 1],
                '10' => [0, 0, 0, 1],
                '10.1' => [2, 0, 1],
                '11' => [0, 0, 1],
                '11.1' => [1, 0, 0, 1],
                '12' => [1, 1, 1],
                '13' => [1, 1, 1],
            ],
            'PROGNAS' => [
                '1' => [1, 1, 1, 1, 1],
                '1.1' => [1, 1, 1],
                '2' => [1, 2, 1, 1],
                '2.1' => [0, 0, 0],
                '2.2' => [1, 1, 1, 1],
                '3' => [2, 1, 1, 1, 1, 1],
                '4' => [1, 1, 1],
                '4.1' => [3, 1],
                '5' => [1, 2, 1, 1],
                '5.1' => [1, 1, 0],
                '6' => [1, 2, 1, 1, 2],
                '6.1' => [1, 2, 1, 1],
            ],
            'TKRS' => [
                '1' => [1, 1, 1, 1],
                '2' => [3, 2, 1],
                '3' => [3, 1, 1, 2],
                '3.1' => [1, 5, 1],
                '4' => [2, 2, 3, 1],
                '5' => [1, 1, 1],
                '6' => [1, 2, 1, 1, 2, 2],
                '7' => [1, 1, 1, 1, 1, 2],
                '7.1' => [1, 2, 1, 1],
                '8' => [1, 1, 1],
                '9' => [1, 3, 1, 2, 1],
                '10' => [1, 1, 1, 1],
                '11' => [1, 1, 1],
                '12' => [1, 1, 1, 3],
                '13' => [2, 3, 1, 1, 3, 1],
                '14' => [1, 2],
                '15' => [3, 2, 2, 1, 2, 2, 2],
            ],
        ]),

        'PPK 1 / EP 1' => ['count' => 1, 'evidence' => '[R] Perjanjian kerja sama dengan institusi penyelenggara pendidikan kesehatan yang masih berlaku.'],
        'PPK 1 / EP 2' => ['count' => 2, 'evidence' => '[D] 1. Daftar institusi pendidikan yang bekerja sama dengan rumah sakit; 2. Sertifikat akreditasi institusi pendidikan.'],
        'PPK 1 / EP 3' => ['count' => 2, 'evidence' => '[R] Pernyataan dalam perjanjian kerja sama yang mencantumkan kriteria penerimaan peserta didik; [D] Daftar peserta didik per periode.'],
        'PPK 1 / EP 4' => ['count' => 1, 'evidence' => '[D] Kajian terhadap hasil evaluasi program pendidikan kesehatan sekurang-kurangnya satu kali setahun.'],
        'PPK 2 / EP 1' => ['count' => 1, 'evidence' => 'Penetapan pengelolaan dan pengawasan pelaksanaan pendidikan klinis yang meliputi poin a-c pada maksud dan tujuan.'],
        'PPK 2 / EP 2' => ['count' => 1, 'evidence' => '[D] Daftar lengkap seluruh peserta pendidikan klinis yang saat ini berada di rumah sakit.'],
        'PPK 2 / EP 3' => ['count' => 1, 'evidence' => '[D] Kelengkapan dokumen peserta pendidikan klinis yang meliputi poin a-e pada maksud dan tujuan.'],
        'PPK 3 / EP 1' => ['count' => 1, 'evidence' => '[D] Perhitungan rasio pendidik klinis dan peserta didik per periode.'],
        'PPK 3 / EP 2' => ['count' => 2, 'evidence' => '1. Perhitungan peserta didik dan data rata-rata jumlah pasien per periode; 2. Bukti pertemuan institusi pendidikan dengan rumah sakit mengenai perhitungan tersebut.'],
        'PPK 3 / EP 3' => ['count' => 1, 'evidence' => '[D] Daftar inventaris sarana prasarana, teknologi dan informasi, serta perpustakaan atau e-library.'],
        'PPK 4 / EP 1' => ['count' => 2, 'evidence' => '1. Penetapan staf klinis sebagai pendidik klinis; 2. Penetapan kewenangan memberikan pendidikan klinis dalam SPK dan RKK.'],
        'PPK 4 / EP 2' => ['count' => 1, 'evidence' => '[D] Daftar staf klinis pemberi pendidikan klinis beserta seluruh gelar akademis dan profesinya.'],
        'PPK 4 / EP 3' => ['count' => 2, 'evidence' => '1. Sertifikat pelatihan pendidik klinis; 2. Sertifikat keprofesian berkelanjutan.'],
        'PPK 5 / EP 1' => ['count' => 1, 'evidence' => 'Penetapan tingkat supervisi setiap peserta pendidikan klinis untuk setiap jenjang pendidikan.'],
        'PPK 5 / EP 2' => ['count' => 3, 'evidence' => '[D] 1. Surat level kompetensi dari institusi pendidikan; 2. Bukti tanda pengenal level kompetensi; 3. Bukti log book peserta didik.'],
        'PPK 5 / EP 3' => ['count' => 1, 'evidence' => '[D] Bukti log book peserta didik dan dokumentasi proses supervisi.'],
        'PPK 5 / EP 4' => ['count' => 1, 'evidence' => 'Bukti pengkajian rekam medis untuk memastikan kewenangan pengisian dan supervisi oleh DPJP.'],
        'PPK 6 / EP 1' => ['count' => 1, 'evidence' => 'Penetapan Komite/Tim Koordinasi Pendidikan atau unit pengelola pendidikan klinis beserta uraian tugas dan tanggung jawab.'],
        'PPK 6 / EP 2' => ['count' => 1, 'evidence' => 'Program orientasi bagi peserta pendidikan klinis.'],
        'PPK 6 / EP 3' => ['count' => 1, 'evidence' => '[D] Bukti pelaksanaan orientasi peserta pendidikan klinis.'],
        'PPK 6 / EP 4' => ['count' => 1, 'evidence' => '[D] Bukti keikutsertaan peserta didik dalam program peningkatan mutu dan keselamatan pasien.'],
        'PPK 6 / EP 5' => ['count' => 1, 'evidence' => 'Monitoring, evaluasi, dan analisis dampak peserta didik terhadap mutu dan keselamatan pasien sekurang-kurangnya setahun sekali.'],
        'PPK 6 / EP 6' => ['count' => 1, 'evidence' => '[D] Hasil survei kepuasan pasien sekurang-kurangnya setahun sekali.'],

        'SKP 1 / EP 1' => ['count' => 1, 'evidence' => '[R] Penetapan sasaran keselamatan pasien meliputi poin 1-6 pada gambaran umum.'],
        'SKP 1 / EP 2' => ['count' => 0, 'evidence' => 'Tidak ada dokumen D/R; bukti penilaian berupa observasi, wawancara, dan/atau simulasi.'],
        'SKP 1 / EP 3' => ['count' => 0, 'evidence' => 'Tidak ada dokumen D/R; bukti penilaian berupa observasi, wawancara, dan/atau simulasi.'],
        'SKP 1 / EP 4' => ['count' => 1, 'evidence' => '[D] Bukti identifikasi pasien pada situasi khusus dan penggunaan label.'],
        'SKP 2 / EP 1' => ['count' => 1, 'evidence' => '[D] Bukti rekam medis komunikasi instruksi melalui telepon dan pelaporan kepada DPJP.'],
        'SKP 2 / EP 2' => ['count' => 2, 'evidence' => '[R] Penetapan hasil kritis pemeriksaan penunjang diagnostik; [D] Bukti rekam medis pelaporan hasil kritis.'],
        'SKP 2 / EP 3' => ['count' => 1, 'evidence' => '[D] Bukti rekam medis serah terima.'],
        'SKP 3 / EP 1' => ['count' => 1, 'evidence' => '[R] Penetapan daftar obat kewaspadaan tinggi termasuk LASA/NORUM.'],
        'SKP 3 / EP 2' => ['count' => 0, 'evidence' => 'Tidak ada dokumen D/R; bukti penilaian berupa observasi dan wawancara.'],
        'SKP 3 / EP 3' => ['count' => 1, 'evidence' => '[D] Bukti evaluasi dan pembaruan daftar obat High-Alert dan LASA/NORUM setahun sekali.'],
        'SKP 3.1 / EP 1' => ['count' => 1, 'evidence' => '[R] Penetapan daftar elektrolit konsentrat yang dapat disimpan di luar instalasi farmasi.'],
        'SKP 3.1 / EP 2' => ['count' => 0, 'evidence' => 'Tidak ada dokumen D/R; bukti penilaian berupa observasi dan wawancara.'],
        'SKP 3.1 / EP 3' => ['count' => 2, 'evidence' => '[R] Penetapan protokol koreksi hipokalemia, hiponatremia, dan hipofosfatemia; [D] Bukti penerapan protokol.'],
        'SKP 4 / EP 1' => ['count' => 1, 'evidence' => '[D] Bukti pelaksanaan verifikasi praoperasi dengan daftar tilik.'],
        'SKP 4 / EP 2' => ['count' => 1, 'evidence' => '[R] Penetapan tanda penandaan sisi operasi/tindakan invasif yang seragam, mudah dikenali, dan tidak bermakna ganda.'],
        'SKP 4 / EP 3' => ['count' => 1, 'evidence' => '[D] Bukti rekam medis site marking.'],
        'SKP 4 / EP 4' => ['count' => 1, 'evidence' => '[D] Bukti rekam medis Time-Out menggunakan Surgical Safety Checklist WHO terkini.'],
        'SKP 5 / EP 1' => ['count' => 0, 'evidence' => 'Tidak ada dokumen D/R; bukti penilaian berupa observasi, wawancara, dan simulasi.'],
        'SKP 5 / EP 2' => ['count' => 1, 'evidence' => '[D] Bukti evaluasi dan upaya perbaikan program kebersihan tangan.'],
        'SKP 6 / EP 1' => ['count' => 1, 'evidence' => '[D] Bukti rekam medis skrining risiko jatuh rawat jalan.'],
        'SKP 6 / EP 2' => ['count' => 1, 'evidence' => '[D] Bukti tindakan/intervensi mengurangi risiko jatuh rawat jalan.'],
        'SKP 6.1 / EP 1' => ['count' => 1, 'evidence' => '[D] Bukti rekam medis pengkajian risiko jatuh rawat inap.'],
        'SKP 6.1 / EP 2' => ['count' => 1, 'evidence' => '[D] Bukti rekam medis pengkajian ulang risiko jatuh.'],
        'SKP 6.1 / EP 3' => ['count' => 1, 'evidence' => '[D] Bukti rekam medis tindakan/intervensi mengurangi risiko jatuh rawat inap.'],

        'KPS 1 / EP 1' => ['count' => 1, 'evidence' => '[R] Penetapan Pedoman Manajemen Sumber Daya Manusia yang meliputi poin a-f pada gambaran umum.'],
        'KPS 1 / EP 2' => ['count' => 1, 'evidence' => '[R] Penetapan persyaratan pendidikan, kompetensi, dan pengalaman staf sesuai peraturan perundang-undangan.'],
        'KPS 1 / EP 3' => ['count' => 2, 'evidence' => '[D] 1. Bukti perencanaan SDM di unit yang disusun secara kolaboratif; 2. Bukti perencanaan SDM sesuai poin a-e dalam maksud dan tujuan.'],
        'KPS 1 / EP 4' => ['count' => 1, 'evidence' => '[D] Bukti perencanaan staf meliputi penghitungan jumlah, jenis, dan kualifikasi staf menggunakan metode sesuai peraturan perundang-undangan.'],
        'KPS 1 / EP 5' => ['count' => 1, 'evidence' => '[D] Bukti perencanaan staf yang membahas penugasan dan rotasi/alih fungsi staf.'],
        'KPS 1 / EP 6' => ['count' => 1, 'evidence' => '[D] Bukti pemantauan efektivitas perencanaan staf secara berkelanjutan dan pembaruan sesuai kebutuhan.'],
        'KPS 2 / EP 1' => ['count' => 1, 'evidence' => '[D] Bukti uraian tugas staf sesuai tugas yang diberikan.'],
        'KPS 2 / EP 2' => ['count' => 1, 'evidence' => '[D] Bukti uraian tugas tenaga medis dan tenaga kesehatan yang diidentifikasi dalam poin a-d pada maksud dan tujuan.'],
        'KPS 3 / EP 1' => ['count' => 1, 'evidence' => '[R] Penetapan proses rekrutmen, evaluasi kompetensi kandidat calon staf, dan mekanisme pengangkatan staf.'],
        'KPS 3 / EP 2' => ['count' => 1, 'evidence' => '[D] Bukti penerapan proses rekrutmen dan evaluasi meliputi poin a-c pada maksud dan tujuan.'],
        'KPS 4 / EP 1' => ['count' => 2, 'evidence' => '[R] Penetapan kompetensi PPA berupa SPK dan RKK sesuai kebutuhan pasien; [D] Bukti penerapan proses penyesuaian kompetensi PPA dengan kebutuhan pasien.'],
        'KPS 4 / EP 2' => ['count' => 1, 'evidence' => '[D] Bukti evaluasi awal PPA baru saat mulai bekerja oleh kepala unit tempat PPA ditugaskan.'],
        'KPS 4 / EP 3' => ['count' => 1, 'evidence' => '[D] Bukti evaluasi setiap PPA sesuai uraian tugas setiap tahun atau sesuai ketentuan rumah sakit.'],
        'KPS 5 / EP 1' => ['count' => 2, 'evidence' => '[R] Penetapan kompetensi staf nonklinis sesuai persyaratan jabatan/posisi; [D] Bukti penerapan proses penyesuaian kompetensi staf nonklinis dengan persyaratan jabatan/posisi.'],
        'KPS 5 / EP 2' => ['count' => 1, 'evidence' => '[D] Bukti penilaian awal kinerja staf nonklinis baru saat akan memulai pekerjaan oleh kepala unit tempat staf ditugaskan.'],
        'KPS 5 / EP 3' => ['count' => 1, 'evidence' => '[D] Bukti evaluasi setiap staf nonklinis sesuai uraian tugas dan tanggung jawab setiap tahun atau sesuai ketentuan rumah sakit.'],
        'KPS 6 / EP 1' => ['count' => 1, 'evidence' => '[D] File kepegawaian staf yang distandardisasi, dipelihara, dan dijaga kerahasiaannya sesuai kebijakan rumah sakit.'],
        'KPS 6 / EP 2' => ['count' => 1, 'evidence' => '[D] Bukti file kepegawaian mencakup poin a-g pada maksud dan tujuan.'],
        'KPS 7 / EP 1' => ['count' => 1, 'evidence' => '[R] Penetapan orientasi umum dan orientasi khusus bagi staf baru.'],
        'KPS 7 / EP 2' => ['count' => 1, 'evidence' => '[D] Bukti orientasi umum dan khusus untuk tenaga medis dan tenaga kesehatan baru.'],
        'KPS 7 / EP 3' => ['count' => 1, 'evidence' => '[D] Bukti orientasi umum dan khusus untuk staf nonklinis baru.'],
        'KPS 7 / EP 4' => ['count' => 1, 'evidence' => '[D] Bukti orientasi umum dan khusus untuk tenaga kontrak, paruh waktu, mahasiswa/trainee, dan sukarelawan.'],
        'KPS 8 / EP 1' => ['count' => 1, 'evidence' => '[D] Bukti hasil identifikasi kebutuhan pendidikan staf berdasarkan sumber informasi poin a-h pada maksud dan tujuan.'],
        'KPS 8 / EP 2' => ['count' => 1, 'evidence' => '[R] Penetapan program pendidikan dan pelatihan berdasarkan hasil identifikasi kebutuhan.'],
        'KPS 8 / EP 3' => ['count' => 1, 'evidence' => '[D] Bukti pendidikan dan pelatihan berkelanjutan bagi staf rumah sakit, baik internal maupun eksternal.'],
        'KPS 8 / EP 4' => ['count' => 1, 'evidence' => '[D] Bukti penyediaan waktu, anggaran, sarana, dan prasarana yang memadai untuk pendidikan dan pelatihan staf.'],
        'KPS 8.1 / EP 1' => ['count' => 1, 'evidence' => '[R] Penetapan pelatihan BHD bagi seluruh staf dan bantuan hidup tingkat lanjut bagi staf yang ditentukan rumah sakit.'],
        'KPS 8.1 / EP 2' => ['count' => 1, 'evidence' => '[D] Bukti staf peserta pelatihan BHD atau bantuan hidup tingkat lanjut telah lulus pelatihan.'],
        'KPS 8.1 / EP 3' => ['count' => 1, 'evidence' => '[D] Bukti pelaksanaan pelatihan setiap dua tahun atau sesuai program pelatihan.'],
        'KPS 9 / EP 1' => ['count' => 1, 'evidence' => '[R] Penetapan program kesehatan dan keselamatan staf.'],
        'KPS 9 / EP 2' => ['count' => 1, 'evidence' => '[D] Bukti pelaksanaan program kesehatan dan keselamatan staf mencakup poin a-h pada maksud dan tujuan.'],
        'KPS 9 / EP 3' => ['count' => 2, 'evidence' => '[D] 1. Hasil identifikasi staf yang terpapar penyakit infeksi; 2. Bukti upaya pencegahan dengan vaksinasi.'],
        'KPS 9 / EP 4' => ['count' => 2, 'evidence' => '[D] 1. Hasil identifikasi risiko staf terpapar atau tertular; 2. Hasil pemeriksaan kesehatan dan vaksinasi.'],
        'KPS 9 / EP 5' => ['count' => 3, 'evidence' => '[D] 1. Bukti pelaksanaan evaluasi; 2. Bukti konseling; 3. Bukti tata laksana lanjutan bagi staf yang terpapar penyakit infeksi.'],
        'KPS 9 / EP 6' => ['count' => 2, 'evidence' => '[D] 1. Daftar area berpotensi terjadi kekerasan di tempat kerja; 2. Bukti upaya mengurangi risiko.'],
        'KPS 9 / EP 7' => ['count' => 3, 'evidence' => '[D] 1. Bukti pelaksanaan evaluasi; 2. Bukti konseling; 3. Bukti tata laksana lanjutan bagi staf yang cedera akibat kekerasan di tempat kerja.'],
        'KPS 10 / EP 1' => ['count' => 1, 'evidence' => '[R] Penetapan peraturan internal tenaga medis yang mengatur penerimaan, kredensial, penilaian kinerja, dan rekredensial.'],
        'KPS 10 / EP 2' => ['count' => 1, 'evidence' => '[D] Bukti pelaksanaan proses kredensial dan pemberian kewenangan klinis untuk staf medis.'],
        'KPS 10 / EP 3' => ['count' => 1, 'evidence' => '[D] Bukti proses kredensial dan pemberian kewenangan klinis kepada staf medis dari luar rumah sakit.'],
        'KPS 10 / EP 4' => ['count' => 1, 'evidence' => '[D] Perjanjian kerja klinis tenaga medis sesuai regulasi rumah sakit.'],
        'KPS 10 / EP 5' => ['count' => 1, 'evidence' => '[D] Bukti verifikasi izin, sertifikat, dan kredensial lain ke lembaga/badan/institusi pendidikan atau organisasi profesional yang diakui.'],
        'KPS 10 / EP 6' => ['count' => 1, 'evidence' => '[D] Bukti kredensial tambahan tenaga medis ke sumber penerbit.'],
        'KPS 10.1 / EP 1' => ['count' => 1, 'evidence' => '[R] Penetapan pengangkatan tenaga medis dalam bentuk SPK.'],
        'KPS 10.1 / EP 2' => ['count' => 2, 'evidence' => '[D] 1. Bukti verifikasi STR dan SIP; 2. SPK dan RKK tenaga medis dengan kewenangan di bawah supervisi maksimal 90 hari.'],
        'KPS 10.1 / EP 3' => ['count' => 2, 'evidence' => '[D] 1. Bukti penunjukan supervisor; 2. Bukti pelaksanaan supervisi tenaga medis yang belum memperoleh kewenangan mandiri.'],
        'KPS 11 / EP 1' => ['count' => 1, 'evidence' => '[R] Penetapan kewenangan klinis dan kewenangan tambahan berdasarkan rekomendasi Komite Medik dalam bentuk RKK dengan mempertimbangkan poin a-j.'],
        'KPS 11 / EP 2' => ['count' => 2, 'evidence' => '[D] 1. Bukti rekomendasi kewenangan klinis dari Komite Medik; 2. Bukti RKK sesuai rekomendasi Komite Medik.'],
        'KPS 11 / EP 3' => ['count' => 2, 'evidence' => '[D] 1. Bukti proses pemberian kewenangan tambahan setelah verifikasi sumber utama; 2. Bukti RKK tambahan.'],
        'KPS 11 / EP 4' => ['count' => 1, 'evidence' => '[D] Bukti SPK dan RKK anggota tenaga medis tersedia di semua unit pelayanan dalam bentuk cetak, elektronik, atau media lain.'],
        'KPS 11 / EP 5' => ['count' => 1, 'evidence' => '[D] Bukti audit pelaksanaan kewenangan klinis tenaga medis sesuai RKK.'],
        'KPS 12 / EP 1' => ['count' => 2, 'evidence' => '[R] Penetapan penilaian kinerja OPPE, etik, dan disiplin tenaga medis; [D] Bukti penerapan proses penilaian kinerja tenaga medis menggunakan OPPE.'],
        'KPS 12 / EP 2' => ['count' => 1, 'evidence' => '[D] Bukti penilaian OPPE yang memuat perilaku, pengembangan profesional, dan kinerja klinis.'],
        'KPS 12 / EP 3' => ['count' => 1, 'evidence' => '[D] Bukti penilaian OPPE yang memuat pencapaian target indikator mutu unit kerja.'],
        'KPS 12 / EP 4' => ['count' => 1, 'evidence' => '[D] Bukti penilaian OPPE berbasis data pelayanan klinis objektif dan, jika memungkinkan, benchmarking eksternal.'],
        'KPS 12 / EP 5' => ['count' => 1, 'evidence' => '[D] Bukti penilaian OPPE setiap 12 bulan.'],
        'KPS 12 / EP 6' => ['count' => 2, 'evidence' => '[D] 1. Bukti laporan insiden keselamatan pasien yang dilakukan tenaga medis; 2. Bukti proses tindak lanjut secara adil (just culture).'],
        'KPS 12 / EP 7' => ['count' => 2, 'evidence' => '[D] 1. Bukti RKK yang diperbarui dalam file tenaga medis; 2. Bukti SPK dan RKK yang diperbarui telah diinformasikan dan disimpan di unit pelayanan.'],
        'KPS 13 / EP 1' => ['count' => 1, 'evidence' => '[D] Bukti rekredensial tenaga medis setiap tiga tahun berdasarkan hasil penilaian OPPE.'],
        'KPS 13 / EP 2' => ['count' => 1, 'evidence' => '[D] Bukti berkas rekredensial dalam file kepegawaian setiap tenaga medis.'],
        'KPS 13 / EP 3' => ['count' => 1, 'evidence' => '[D] Bukti pemberian kewenangan klinis tambahan berdasarkan kredensial yang telah diverifikasi dari sumber penyelenggara pendidikan atau pelatihan.'],
        'KPS 14 / EP 1' => ['count' => 2, 'evidence' => '[R] Penetapan proses kredensial tenaga perawat meliputi poin a-c; [D] Bukti penerapan proses kredensial keperawatan sesuai regulasi.'],
        'KPS 14 / EP 2' => ['count' => 1, 'evidence' => '[D] Bukti berkas kredensial dalam file tenaga keperawatan.'],
        'KPS 14 / EP 3' => ['count' => 1, 'evidence' => '[D] Bukti verifikasi kredensial tenaga perawat ke sumber utama.'],
        'KPS 14 / EP 4' => ['count' => 1, 'evidence' => '[D] Bukti berkas kredensial dipelihara dalam file kepegawaian setiap tenaga perawat.'],
        'KPS 14 / EP 5' => ['count' => 1, 'evidence' => '[D] Bukti berkas kredensial perawat kontrak lengkap sebelum penugasan.'],
        'KPS 15 / EP 1' => ['count' => 1, 'evidence' => '[R] Penetapan RKK berdasarkan hasil kredensial perawat.'],
        'KPS 15 / EP 2' => ['count' => 1, 'evidence' => '[R] Penetapan SPK tenaga perawat sesuai peraturan perundang-undangan.'],
        'KPS 16 / EP 1' => ['count' => 2, 'evidence' => '[R] Penetapan penilaian kinerja tenaga perawat; [D] Bukti penilaian kinerja tenaga perawat secara periodik.'],
        'KPS 16 / EP 2' => ['count' => 1, 'evidence' => '[D] Bukti penilaian kinerja tenaga perawat yang memuat pemenuhan uraian tugas dan peran dalam pencapaian target indikator mutu unit.'],
        'KPS 16 / EP 3' => ['count' => 2, 'evidence' => '[D] 1. Bukti laporan insiden keselamatan pasien yang dilakukan tenaga perawat; 2. Bukti proses tindak lanjut secara adil (just culture).'],
        'KPS 16 / EP 4' => ['count' => 1, 'evidence' => '[D] Bukti hasil kajian, tindakan yang diambil, dan dampaknya atas tanggung jawab pekerjaan dalam file kredensial perawat.'],
        'KPS 17 / EP 1' => ['count' => 2, 'evidence' => '[R] Penetapan proses kredensial tenaga kesehatan lain meliputi poin a-c; [D] Bukti penerapan proses kredensial tenaga kesehatan lain sesuai regulasi.'],
        'KPS 17 / EP 2' => ['count' => 1, 'evidence' => '[D] Bukti berkas kredensial dalam file tenaga kesehatan lain.'],
        'KPS 17 / EP 3' => ['count' => 1, 'evidence' => '[D] Bukti verifikasi kredensial tenaga kesehatan lain ke sumber utama.'],
        'KPS 17 / EP 4' => ['count' => 1, 'evidence' => '[D] Bukti berkas kredensial dipelihara untuk setiap tenaga kesehatan lain.'],
        'KPS 18 / EP 1' => ['count' => 1, 'evidence' => '[R] Penetapan RKK PPA lain dan staf klinis lain berdasarkan hasil kredensial.'],
        'KPS 18 / EP 2' => ['count' => 1, 'evidence' => '[R] Penetapan SPK tenaga kesehatan lain sesuai peraturan perundang-undangan.'],
        'KPS 19 / EP 1' => ['count' => 2, 'evidence' => '[R] Penetapan penilaian kinerja tenaga kesehatan lain; [D] Bukti penilaian kinerja tenaga kesehatan lain secara periodik.'],
        'KPS 19 / EP 2' => ['count' => 1, 'evidence' => '[D] Bukti penilaian kinerja tenaga kesehatan lain yang memuat pemenuhan uraian tugas dan peran dalam pencapaian target indikator mutu unit.'],
        'KPS 19 / EP 3' => ['count' => 2, 'evidence' => '[D] 1. Bukti laporan insiden keselamatan pasien yang dilakukan tenaga kesehatan lain; 2. Bukti proses tindak lanjut secara adil (just culture).'],
        'KPS 19 / EP 4' => ['count' => 1, 'evidence' => '[D] Bukti hasil kajian, tindakan yang diambil, dan dampaknya atas tanggung jawab pekerjaan dalam file kredensial tenaga kesehatan lain.'],

        'MFK 1 / EP 1' => ['count' => 1, 'evidence' => '[R] Pedoman Manajemen Fasilitas dan Keselamatan yang meliputi poin a-j pada gambaran umum.'],
        'MFK 1 / EP 2' => ['count' => 5, 'evidence' => '[D] 1. Perizinan berusaha dan registrasi Kementerian Kesehatan; 2. Izin Pengelolaan Limbah Cair; 3. Izin/kerja sama pengolahan dan pengangkutan limbah B3; 4. Izin radiologi; 5. Izin lain sesuai peraturan perundang-undangan.'],
        'MFK 1 / EP 3' => ['count' => 1, 'evidence' => '[D] Bukti perencanaan anggaran dan sumber daya yang memenuhi persyaratan perundang-undangan.'],
        'MFK 2 / EP 1' => ['count' => 1, 'evidence' => '[R] Penetapan penanggung jawab MFK yang kompeten dan berpengalaman, dilengkapi uraian tugas dan tanggung jawab poin a-j.'],
        'MFK 2 / EP 2' => ['count' => 1, 'evidence' => '[R] Program Manajemen Fasilitas dan Keselamatan yang meliputi poin a-j pada maksud dan tujuan.'],
        'MFK 2 / EP 3' => ['count' => 1, 'evidence' => '[D] Bukti pelaksanaan pengawasan dan evaluasi MFK setiap tahun meliputi poin a-g.'],
        'MFK 2 / EP 4' => ['count' => 1, 'evidence' => '[D] Bukti penerapan program MFK pada tenant/penyewa lahan meliputi poin a-e.'],
        'MFK 3 / EP 1' => ['count' => 1, 'evidence' => '[D] Bukti penerapan program pengelolaan keselamatan rumah sakit meliputi poin a-c.'],
        'MFK 3 / EP 2' => ['count' => 1, 'evidence' => '[R] Program Kesehatan dan Keselamatan Kerja yang terintegrasi dengan program MFK.'],
        'MFK 3 / EP 3' => ['count' => 1, 'evidence' => '[D] Daftar risiko/risk register terkait keselamatan rumah sakit setiap tahun.'],
        'MFK 3 / EP 4' => ['count' => 1, 'evidence' => '[D] Bukti hasil pemantauan risiko keselamatan dan laporan kepada pimpinan rumah sakit setiap enam bulan.'],
        'MFK 4 / EP 1' => ['count' => 1, 'evidence' => '[D] Bukti penerapan proses pengelolaan keamanan rumah sakit meliputi poin a-e.'],
        'MFK 4 / EP 2' => ['count' => 1, 'evidence' => '[D] Daftar risiko/risk register terkait keamanan setiap tahun.'],
        'MFK 4 / EP 3' => ['count' => 1, 'evidence' => '[D] Daftar risiko/risk register terkait keselamatan rumah sakit setiap tahun.'],
        'MFK 4 / EP 4' => ['count' => 1, 'evidence' => '[D] Laporan pemantauan risiko keamanan kepada Direktur setiap enam bulan.'],
        'MFK 5 / EP 1' => ['count' => 1, 'evidence' => '[D] Bukti pelaksanaan pengelolaan B3 meliputi poin a-h.'],
        'MFK 5 / EP 2' => ['count' => 1, 'evidence' => '[D] Bukti pengkajian risiko pengelolaan B3 dan limbah B3 dalam risk register.'],
        'MFK 5 / EP 3' => ['count' => 1, 'evidence' => '[D] Daftar lokasi dan jumlah eye washer/body washer.'],
        'MFK 5 / EP 4' => ['count' => 0, 'evidence' => 'Tidak ada dokumen D/R; bukti penilaian berupa wawancara dan simulasi penanganan tumpahan B3.'],
        'MFK 5 / EP 5' => ['count' => 0, 'evidence' => 'Tidak ada dokumen D/R; bukti penilaian berupa wawancara, observasi, dan simulasi pengelolaan B3.'],
        'MFK 5.1 / EP 1' => ['count' => 0, 'evidence' => 'Tidak ada dokumen D/R; bukti penilaian berupa observasi TPS B3 dan wawancara.'],
        'MFK 5.1 / EP 2' => ['count' => 1, 'evidence' => '[D] Perjanjian kerja sama dengan transporter dan pengolah limbah B3 berizin yang masih berlaku.'],
        'MFK 5.1 / EP 3' => ['count' => 1, 'evidence' => '[D] Bukti pengelolaan limbah cair, izin IPAL, atau izin pembuangan limbah cair.'],
        'MFK 6 / EP 1' => ['count' => 1, 'evidence' => '[D] Bukti pengkajian risiko kebakaran secara proaktif meliputi poin a-i setiap tahun.'],
        'MFK 6 / EP 2' => ['count' => 1, 'evidence' => '[D] Bukti penerapan proses proteksi kebakaran meliputi poin a-f.'],
        'MFK 6 / EP 3' => ['count' => 1, 'evidence' => '[R] Penetapan rumah sakit sebagai kawasan bebas rokok.'],
        'MFK 6 / EP 4' => ['count' => 1, 'evidence' => '[D] Daftar risiko proteksi kebakaran.'],
        'MFK 6 / EP 5' => ['count' => 2, 'evidence' => '[D] 1. Bukti pelatihan penanggulangan kebakaran; 2. Laporan simulasi kebakaran tahunan beserta debriefing.'],
        'MFK 6 / EP 6' => ['count' => 2, 'evidence' => '[D] 1. Daftar inventaris peralatan proteksi aktif dan pasif; 2. Bukti pemeriksaan, uji coba, dan pemeliharaan peralatan proteksi kebakaran.'],
        'MFK 7 / EP 1' => ['count' => 1, 'evidence' => '[D] Bukti penerapan proses pengelolaan peralatan medis meliputi poin a-e.'],
        'MFK 7 / EP 2' => ['count' => 2, 'evidence' => '[R] Penetapan penanggung jawab pengelolaan dan pengawasan peralatan medis; [D] Bukti kompetensi penanggung jawab.'],
        'MFK 7 / EP 3' => ['count' => 1, 'evidence' => '[D] Daftar inventaris seluruh peralatan medis yang dilengkapi daftar risiko/risk register.'],
        'MFK 7 / EP 4' => ['count' => 2, 'evidence' => '[D] 1. Bukti perbaikan alat oleh pihak berwenang; 2. Bukti sertifikasi pihak ketiga yang melakukan perbaikan.'],
        'MFK 7 / EP 5' => ['count' => 2, 'evidence' => '[D] 1. Bukti pemantauan peralatan medis; 2. Bukti penarikan/recall peralatan medis.'],
        'MFK 7 / EP 6' => ['count' => 1, 'evidence' => '[D] Laporan insiden keselamatan pasien terkait peralatan medis sesuai peraturan perundang-undangan.'],
        'MFK 8 / EP 1' => ['count' => 1, 'evidence' => '[D] Bukti proses pengelolaan sistem utilitas meliputi poin a-e.'],
        'MFK 8 / EP 2' => ['count' => 1, 'evidence' => '[D] Daftar risiko sistem utilitas dan komponen kritis setiap tahun.'],
        'MFK 8.1 / EP 1' => ['count' => 1, 'evidence' => '[D] Daftar inventaris sistem utilitas dan komponen kritis setiap tahun.'],
        'MFK 8.1 / EP 2' => ['count' => 1, 'evidence' => '[D] Bukti inspeksi berkala sistem utilitas dan komponen kritis.'],
        'MFK 8.1 / EP 3' => ['count' => 1, 'evidence' => '[D] Bukti uji fungsi berkala sistem utilitas dan komponen kritis.'],
        'MFK 8.1 / EP 4' => ['count' => 1, 'evidence' => '[D] Bukti pemeliharaan sistem utilitas dan komponen kritis.'],
        'MFK 8.1 / EP 5' => ['count' => 1, 'evidence' => '[D] Bukti perbaikan sistem utilitas dan komponen kritis bila diperlukan.'],
        'MFK 8.2 / EP 1' => ['count' => 1, 'evidence' => '[R] Penetapan proses sistem utilitas untuk keadaan darurat meliputi poin a-e.'],
        'MFK 8.2 / EP 2' => ['count' => 0, 'evidence' => 'Tidak ada dokumen D/R; bukti penilaian berupa observasi persediaan air bersih dan wawancara.'],
        'MFK 8.2 / EP 3' => ['count' => 0, 'evidence' => 'Tidak ada dokumen D/R; bukti penilaian berupa observasi sumber listrik utama/cadangan dan wawancara.'],
        'MFK 8.2 / EP 4' => ['count' => 1, 'evidence' => '[D] Bukti identifikasi area berisiko tinggi bila listrik atau air bersih terganggu/terkontaminasi.'],
        'MFK 8.2 / EP 5' => ['count' => 1, 'evidence' => '[D] Kontrak kerja sama penyedia listrik dan air bersih untuk keadaan darurat.'],
        'MFK 8.2.1 / EP 1' => ['count' => 1, 'evidence' => '[D] Bukti uji coba sumber air bersih dan listrik cadangan sekurang-kurangnya setiap enam bulan.'],
        'MFK 8.2.1 / EP 2' => ['count' => 1, 'evidence' => '[D] Dokumentasi hasil uji coba sumber air bersih cadangan/alternatif.'],
        'MFK 8.2.1 / EP 3' => ['count' => 1, 'evidence' => '[D] Dokumentasi hasil uji coba sumber listrik cadangan/alternatif.'],
        'MFK 8.2.1 / EP 4' => ['count' => 0, 'evidence' => 'Tidak ada dokumen D/R; bukti penilaian berupa observasi dan wawancara ketersediaan bahan bakar sumber listrik cadangan.'],
        'MFK 8.3 / EP 1' => ['count' => 1, 'evidence' => '[D] Bukti pelaksanaan pemeriksaan air bersih dan air limbah meliputi poin a-d.'],
        'MFK 8.3 / EP 2' => ['count' => 1, 'evidence' => '[D] Bukti pemantauan dan evaluasi mutu air bersih.'],
        'MFK 8.3 / EP 3' => ['count' => 1, 'evidence' => '[D] Bukti tindak lanjut hasil pemantauan dan evaluasi mutu air bersih.'],
        'MFK 9 / EP 1' => ['count' => 1, 'evidence' => '[D] Bukti penerapan proses pengelolaan bencana meliputi poin a-h.'],
        'MFK 9 / EP 2' => ['count' => 1, 'evidence' => '[D] Hasil Hazard Vulnerability Analysis tahunan yang terintegrasi dengan risk register dan profil risiko.'],
        'MFK 9 / EP 3' => ['count' => 1, 'evidence' => '[R] Program pengelolaan bencana berdasarkan hasil Hazard Vulnerability Analysis setiap tahun.'],
        'MFK 9 / EP 4' => ['count' => 1, 'evidence' => '[D] Bukti simulasi kesiapan menghadapi kedaruratan, wabah, dan bencana minimal setahun sekali beserta debriefing.'],
        'MFK 9 / EP 5' => ['count' => 0, 'evidence' => 'Tidak ada dokumen D/R; bukti penilaian berupa wawancara dan simulasi prosedur penanganan kedaruratan/bencana.'],
        'MFK 9 / EP 6' => ['count' => 0, 'evidence' => 'Tidak ada dokumen D/R; bukti penilaian berupa observasi ruang dekontaminasi di Instalasi Gawat Darurat.'],
        'MFK 10 / EP 1' => ['count' => 1, 'evidence' => '[D] Hasil asesmen risiko prakonstruksi/PCRA meliputi poin a-j.'],
        'MFK 10 / EP 2' => ['count' => 1, 'evidence' => '[D] Bukti pelaksanaan PCRA bila terdapat rencana konstruksi, renovasi, atau demolisi.'],
        'MFK 10 / EP 3' => ['count' => 1, 'evidence' => '[D] Bukti tindak lanjut PCRA untuk meminimalkan risiko selama pembongkaran, konstruksi, dan renovasi.'],
        'MFK 10 / EP 4' => ['count' => 1, 'evidence' => '[D] Bukti audit kepatuhan kontraktor terhadap implementasi PCRA.'],
        'MFK 11 / EP 1' => ['count' => 1, 'evidence' => '[D] Bukti pelatihan program MFK terkait keselamatan bagi semua staf setiap tahun.'],
        'MFK 11 / EP 2' => ['count' => 1, 'evidence' => '[D] Bukti pelatihan program MFK terkait keamanan bagi semua staf setiap tahun.'],
        'MFK 11 / EP 3' => ['count' => 1, 'evidence' => '[D] Bukti pelatihan program MFK terkait pengelolaan B3 bagi semua staf setiap tahun.'],
        'MFK 11 / EP 4' => ['count' => 1, 'evidence' => '[D] Bukti pelatihan program MFK terkait proteksi kebakaran bagi semua staf setiap tahun.'],
        'MFK 11 / EP 5' => ['count' => 1, 'evidence' => '[D] Bukti pelatihan program MFK terkait peralatan medis bagi staf terkait setiap tahun.'],
        'MFK 11 / EP 6' => ['count' => 1, 'evidence' => '[D] Bukti pelatihan program MFK terkait sistem utilitas bagi staf terkait setiap tahun.'],
        'MFK 11 / EP 7' => ['count' => 1, 'evidence' => '[D] Bukti pelatihan program MFK terkait penanganan bencana bagi semua staf setiap tahun.'],
        'MFK 11 / EP 8' => ['count' => 1, 'evidence' => '[D] Bukti pelatihan pengelolaan fasilitas dan keselamatan bagi vendor, pekerja kontrak, relawan, pelajar, peserta didik/pelatihan, dan pihak lain yang relevan.'],

        'MRMIK 1 / EP 1' => ['count' => 1, 'evidence' => '[R] Penetapan kebijakan pengelolaan sistem informasi rumah sakit meliputi poin a-g pada gambaran umum.'],
        'MRMIK 1 / EP 2' => ['count' => 1, 'evidence' => '[D] Bukti penerapan pengelolaan informasi untuk memenuhi kebutuhan internal dan eksternal rumah sakit.'],
        'MRMIK 1 / EP 3' => ['count' => 1, 'evidence' => '[D] Bukti penerapan sistem informasi sesuai ukuran rumah sakit, kompleksitas layanan, staf terlatih, serta sumber daya teknis dan lainnya.'],
        'MRMIK 1 / EP 4' => ['count' => 2, 'evidence' => '[D] 1. Bukti pemantauan dan evaluasi berkala pemenuhan informasi internal/eksternal; 2. Bukti upaya perbaikan sesuai hasil pemantauan dan evaluasi.'],
        'MRMIK 1 / EP 5' => ['count' => 1, 'evidence' => '[D] Bukti ketersediaan data dan informasi terkini yang mendukung asuhan pasien, pendidikan, dan riset bila program tersebut diselenggarakan.'],
        'MRMIK 2 / EP 1' => ['count' => 1, 'evidence' => '[D] Bukti pelatihan prinsip pengelolaan dan penggunaan sistem informasi bagi PPA, pimpinan, kepala departemen/unit, dan staf.'],
        'MRMIK 2 / EP 2' => ['count' => 1, 'evidence' => '[D] Bukti integrasi data dan informasi klinis serta nonklinis untuk mendukung pengambilan keputusan.'],
        'MRMIK 2.1 / EP 1' => ['count' => 0, 'evidence' => 'Tidak ada dokumen D/R; bukti penilaian berupa observasi dan wawancara penerapan kerahasiaan, keamanan, dan integritas data.'],
        'MRMIK 2.1 / EP 2' => ['count' => 0, 'evidence' => 'Tidak ada dokumen D/R; bukti penilaian berupa observasi dan wawancara penerapan hak akses data.'],
        'MRMIK 2.1 / EP 3' => ['count' => 2, 'evidence' => '[D] 1. Bukti pemantauan kepatuhan kerahasiaan, keamanan, dan integritas data; 2. Bukti tindak lanjut pelanggaran.'],
        'MRMIK 2.2 / EP 1' => ['count' => 0, 'evidence' => 'Tidak ada dokumen D/R; bukti penilaian berupa observasi perlindungan tempat penyimpanan rekam medis dan sistem teknologi informasi.'],
        'MRMIK 2.2 / EP 2' => ['count' => 1, 'evidence' => '[D] Bukti pemantauan dan evaluasi keamanan data dan informasi.'],
        'MRMIK 2.2 / EP 3' => ['count' => 1, 'evidence' => '[D] Bukti tindakan perbaikan untuk meningkatkan keamanan data dan informasi.'],
        'MRMIK 3 / EP 1' => ['count' => 1, 'evidence' => '[R] Penetapan Pedoman Tata Naskah meliputi poin a-h pada maksud dan tujuan.'],
        'MRMIK 3 / EP 2' => ['count' => 1, 'evidence' => '[D] Bukti penerapan format seragam untuk semua dokumen sejenis sesuai pedoman tata naskah.'],
        'MRMIK 3 / EP 3' => ['count' => 1, 'evidence' => '[D] Bukti dokumen internal mencakup poin a-c pada maksud dan tujuan.'],
        'MRMIK 4 / EP 1' => ['count' => 1, 'evidence' => '[D] Bukti penyebaran data dan informasi internal/eksternal secara tepat waktu, berformat seragam, dan sesuai frekuensi.'],
        'MRMIK 4 / EP 2' => ['count' => 1, 'evidence' => '[D] Bukti data dan informasi perawatan pasien diterima tepat waktu, berformat seragam, dan sesuai kebutuhan.'],
        'MRMIK 5 / EP 1' => ['count' => 1, 'evidence' => '[R] Penetapan Pedoman Penyelenggaraan Rekam Medis Elektronik.'],
        'MRMIK 5 / EP 2' => ['count' => 2, 'evidence' => '[R] 1. Pedoman Organisasi Unit Penyelenggara Rekam Medis; 2. SK penunjukan pengelola rekam medis yang kompeten beserta uraian tugas dan wewenang.'],
        'MRMIK 5 / EP 3' => ['count' => 1, 'evidence' => '[D] Bukti penyelenggaraan rekam medis elektronik sejak pasien masuk hingga pulang, dirujuk, atau meninggal.'],
        'MRMIK 5 / EP 4' => ['count' => 1, 'evidence' => '[D] Bukti audit pengelolaan rekam medis elektronik yang menjamin keamanan dan kerahasiaan.'],
        'MRMIK 6 / EP 1' => ['count' => 0, 'evidence' => 'Tidak ada dokumen D/R; bukti penilaian berupa observasi dan wawancara sistem penomoran rekam medis.'],
        'MRMIK 6 / EP 2' => ['count' => 1, 'evidence' => '[D] Bukti rekam medis rawat jalan, rawat inap, gawat darurat, dan pemeriksaan penunjang disusun serta diisi sesuai ketetapan.'],
        'MRMIK 6 / EP 3' => ['count' => 1, 'evidence' => '[D] Bukti evaluasi dan pembaruan formulir rekam medis secara periodik.'],
        'MRMIK 7 / EP 1' => ['count' => 1, 'evidence' => '[D] Bukti rekam medis elektronik berisi informasi sesuai ketetapan rumah sakit dan peraturan perundang-undangan.'],
        'MRMIK 7 / EP 2' => ['count' => 1, 'evidence' => '[D] Bukti rekam medis elektronik memuat informasi memadai sesuai poin a-f pada maksud dan tujuan.'],
        'MRMIK 8 / EP 1' => ['count' => 1, 'evidence' => '[D] Bukti rekam medis elektronik mencantumkan identitas PPA secara jelas.'],
        'MRMIK 8 / EP 2' => ['count' => 1, 'evidence' => '[D] Bukti rekam medis elektronik mencantumkan tanggal dan waktu penulisan oleh PPA.'],
        'MRMIK 8 / EP 3' => ['count' => 1, 'evidence' => '[R] Penetapan prosedur koreksi penulisan rekam medis elektronik dan nonelektronik.'],
        'MRMIK 8 / EP 4' => ['count' => 2, 'evidence' => '[D] 1. Bukti pemantauan dan evaluasi penulisan identitas, tanggal, waktu, dan koreksi rekam medis; 2. Rencana tindak lanjut hasil evaluasi.'],
        'MRMIK 9 / EP 1' => ['count' => 1, 'evidence' => '[R] Penetapan kode diagnosis, kode prosedur, singkatan, dan simbol dalam rekam medis.'],
        'MRMIK 9 / EP 2' => ['count' => 2, 'evidence' => '[D] 1. Bukti evaluasi penggunaan kode diagnosis, prosedur, singkatan, dan simbol; 2. Bukti perbaikan sesuai hasil evaluasi.'],
        'MRMIK 10 / EP 1' => ['count' => 1, 'evidence' => '[R] Penetapan otoritas pengisian rekam medis termasuk isi dan formatnya.'],
        'MRMIK 10 / EP 2' => ['count' => 1, 'evidence' => '[R] Penetapan hak akses dalam pelepasan informasi rekam medis.'],
        'MRMIK 10 / EP 3' => ['count' => 1, 'evidence' => '[D] Bukti rekam medis elektronik maupun kertas terjamin otentifikasi, keamanan, dan kerahasiaannya.'],
        'MRMIK 11 / EP 1' => ['count' => 2, 'evidence' => '[R] 1. Penetapan jangka waktu penyimpanan rekam medis, data, dan informasi pasien; 2. Penetapan prosedur pemusnahan rekam medis.'],
        'MRMIK 11 / EP 2' => ['count' => 1, 'evidence' => '[D] Bukti pelaksanaan dan berita acara pemusnahan rekam medis sesuai peraturan perundang-undangan.'],
        'MRMIK 11 / EP 3' => ['count' => 1, 'evidence' => '[D] Bukti data/informasi pasien yang bernilai guna disimpan secara permanen.'],
        'MRMIK 12 / EP 1' => ['count' => 1, 'evidence' => '[R] Penetapan komite/tim rekam medis beserta uraian tugas, tanggung jawab, dan wewenang.'],
        'MRMIK 12 / EP 2' => ['count' => 1, 'evidence' => '[D] Bukti evaluasi pengkajian rekam medis tahunan menggunakan sampel yang mewakili.'],
        'MRMIK 12 / EP 3' => ['count' => 1, 'evidence' => '[D] Bukti pengkajian rekam medis berfokus pada ketepatan waktu, keterbacaan, kelengkapan, dan kesesuaian isi.'],
        'MRMIK 12 / EP 4' => ['count' => 2, 'evidence' => '[D] 1. Hasil pengkajian rekam medis yang dilaporkan kepada pimpinan; 2. Bukti tindak lanjut sebagai upaya perbaikan.'],
        'MRMIK 13 / EP 1' => ['count' => 1, 'evidence' => '[R] Penetapan Pedoman Sistem Informasi Rumah Sakit.'],
        'MRMIK 13 / EP 2' => ['count' => 1, 'evidence' => '[D] Bukti penerapan Sistem Informasi Rumah Sakit sesuai ketetapan dan peraturan perundang-undangan.'],
        'MRMIK 13 / EP 3' => ['count' => 2, 'evidence' => '[R] 1. Pedoman pengorganisasian unit penyelenggara SIMRS; 2. SK penunjukan staf kompeten yang memimpin unit beserta uraian tugas dan wewenang.'],
        'MRMIK 13 / EP 4' => ['count' => 1, 'evidence' => '[D] Bukti integrasi data dan informasi klinis serta nonklinis untuk mendukung pengambilan keputusan.'],
        'MRMIK 13 / EP 5' => ['count' => 2, 'evidence' => '[D] 1. Bukti penilaian efektivitas sistem rekam medis elektronik; 2. Rencana tindak lanjut perbaikan berdasarkan hasil penilaian.'],
        'MRMIK 13.1 / EP 1' => ['count' => 1, 'evidence' => '[R] Penetapan prosedur penanganan waktu henti sistem data untuk menjaga pelayanan.'],
        'MRMIK 13.1 / EP 2' => ['count' => 1, 'evidence' => '[D] Bukti pelatihan staf mengenai prosedur penanganan waktu henti sistem data terencana maupun tidak terencana.'],
        'MRMIK 13.1 / EP 3' => ['count' => 2, 'evidence' => '[D] 1. Bukti evaluasi pascawaktu henti sistem data; 2. Rencana tindak lanjut perbaikan untuk kejadian berikutnya.'],

        'PMKP 1 / EP 1' => ['count' => 1, 'evidence' => '[R] Penetapan Pedoman PMKP serta manajemen risiko.'],
        'PMKP 1 / EP 2' => ['count' => 3, 'evidence' => '[R] 1. Penetapan Komite/Tim Mutu RS; 2. Pedoman kerja; 3. Program kerja Komite/Tim Mutu RS.'],
        'PMKP 1 / EP 3' => ['count' => 1, 'evidence' => '[R] Penetapan program PMKP RS oleh Direktur dan pengesahan representatif pemilik/dewan pengawas.'],
        'PMKP 1 / EP 4' => ['count' => 1, 'evidence' => '[D] Bukti evaluasi program PMKP dalam rapat koordinasi triwulan.'],
        'PMKP 2 / EP 1' => ['count' => 1, 'evidence' => '[D] Bukti rapat pemilihan indikator mutu prioritas.'],
        'PMKP 2 / EP 2' => ['count' => 2, 'evidence' => '[D] 1. Bukti rapat koordinasi dan integrasi pengukuran; 2. Bukti supervisi ke unit layanan.'],
        'PMKP 2 / EP 3' => ['count' => 2, 'evidence' => '[D] 1. Bukti integrasi laporan insiden dan pengukuran budaya keselamatan; 2. Bukti solusi/perbaikan terintegrasi.'],
        'PMKP 3 / EP 1' => ['count' => 1, 'evidence' => '[D] Bukti pengumpulan data INM, IMP-RS, dan IMP-Unit.'],
        'PMKP 3 / EP 2' => ['count' => 1, 'evidence' => '[R] Profil indikator IMP-RS dan IMP-Unit mencakup poin a-t.'],
        'PMKP 4 / EP 1' => ['count' => 1, 'evidence' => '[D] Bukti agregasi dan analisis seluruh indikator mutu.'],
        'PMKP 4 / EP 2' => ['count' => 1, 'evidence' => '[D] Laporan triwulan hasil analisis yang memuat rekomendasi tindakan perbaikan dan efisiensi penggunaan sumber daya.'],
        'PMKP 4 / EP 3' => ['count' => 1, 'evidence' => '[D] Bukti laporan triwulan kepada Direktur dan representatif pemilik/dewan pengawas.'],
        'PMKP 4 / EP 4' => ['count' => 2, 'evidence' => '[D] 1. Bukti e-report INM ke Kementerian Kesehatan; 2. Bukti e-report IKP ke KNKP.'],
        'PMKP 4 / EP 5' => ['count' => 1, 'evidence' => '[D] Bukti pelaksanaan pembelajaran menggunakan database eksternal untuk perbandingan internal, RS setara, praktik terbaik, dan sumber ilmiah profesional.'],
        'PMKP 4 / EP 6' => ['count' => 1, 'evidence' => '[D] Bukti keamanan dan kerahasiaan pelaporan database eksternal.'],
        'PMKP 4 / EP 7' => ['count' => 1, 'evidence' => '[D] Bukti analisis efisiensi biaya dan sumber daya pada proyek prioritas.'],
        'PMKP 4.1 / EP 1' => ['count' => 1, 'evidence' => '[D] Bukti pengumpulan dan analisis data menjadi informasi perbaikan.'],
        'PMKP 4.1 / EP 2' => ['count' => 1, 'evidence' => '[D] Sertifikat pelatihan PMKP staf pengukuran.'],
        'PMKP 4.1 / EP 3' => ['count' => 1, 'evidence' => '[D] Bukti pelaporan hasil analisis kepada penanggung jawab indikator.'],
        'PMKP 5 / EP 1' => ['count' => 1, 'evidence' => '[D] Bukti validasi data sesuai poin a-f.'],
        'PMKP 5 / EP 2' => ['count' => 1, 'evidence' => '[D] Bukti validasi data yang dipublikasikan.'],
        'PMKP 6 / EP 1' => ['count' => 4, 'evidence' => '[D] 1. Rencana perbaikan; 2. Uji coba skala kecil; 3. Analisis hasil uji coba; 4. Penerapan luas.'],
        'PMKP 6 / EP 2' => ['count' => 6, 'evidence' => '[D] 1. Pengumpulan data; 2. Validasi; 3. Analisis; 4. Rencana perbaikan; 5. Implementasi; 6. Bukti perbaikan berkelanjutan.'],
        'PMKP 6 / EP 3' => ['count' => 1, 'evidence' => '[D] Bukti perubahan regulasi/proses untuk mempertahankan perbaikan.'],
        'PMKP 6 / EP 4' => ['count' => 1, 'evidence' => '[D] Bukti keberhasilan dalam laporan triwulan.'],
        'PMKP 7 / EP 1' => ['count' => 2, 'evidence' => '[D] 1. Bukti evaluasi clinical pathway; 2. Clinical pathway berbasis PPK.'],
        'PMKP 7 / EP 2' => ['count' => 1, 'evidence' => '[D] Bukti capaian kepatuhan DPJP dan pengurangan variasi clinical pathway.'],
        'PMKP 7 / EP 3' => ['count' => 1, 'evidence' => '[D] Bukti audit klinis/medis pada prioritas standar pelayanan kedokteran.'],
        'PMKP 8 / EP 1' => ['count' => 1, 'evidence' => '[R] Pedoman Sistem Pelaporan dan Pembelajaran Keselamatan Pasien Rumah Sakit.'],
        'PMKP 8 / EP 2' => ['count' => 1, 'evidence' => '[R] Penetapan tim investigator ad hoc untuk investigasi komprehensif/RCA kejadian sentinel.'],
        'PMKP 8 / EP 3' => ['count' => 1, 'evidence' => '[D] Bukti tindakan korektif dan pemantauan efektivitas hasil RCA.'],
        'PMKP 8 / EP 4' => ['count' => 1, 'evidence' => '[R] Ketentuan investigasi sederhana sesuai grading dalam Pedoman SP2KP.'],
        'PMKP 8 / EP 5' => ['count' => 1, 'evidence' => '[D] Bukti tindakan korektif dan pemantauan hasil investigasi sederhana.'],
        'PMKP 9 / EP 1' => ['count' => 3, 'evidence' => '[D] 1. Pengumpulan data insiden; 2. Analisis insiden; 3. Pelaporan insiden.'],
        'PMKP 9 / EP 2' => ['count' => 1, 'evidence' => '[D] Bukti RCA/simple RCA ketika terjadi tingkat, pola, atau tren tak diharapkan.'],
        'PMKP 9 / EP 3' => ['count' => 1, 'evidence' => '[D] Laporan triwulan outcome insiden keselamatan pasien.'],
        'PMKP 10 / EP 1' => ['count' => 1, 'evidence' => '[D] Hasil survei dan evaluasi budaya keselamatan pasien tahunan.'],
        'PMKP 10 / EP 2' => ['count' => 1, 'evidence' => '[R] Penetapan program budaya keselamatan pasien berdasarkan hasil survei.'],
        'PMKP 11 / EP 1' => ['count' => 1, 'evidence' => '[D] Bukti supervisi penerapan program manajemen risiko.'],
        'PMKP 11 / EP 2' => ['count' => 1, 'evidence' => '[D] Daftar risiko rumah sakit berdasarkan daftar risiko unit.'],
        'PMKP 11 / EP 3' => ['count' => 1, 'evidence' => '[D] Profil risiko dan rencana penanganan.'],
        'PMKP 11 / EP 4' => ['count' => 3, 'evidence' => '[D] 1. Ceklis pemantauan; 2. Hasil pemantauan; 3. Laporan hasil pemantauan enam bulanan.'],
        'PMKP 11 / EP 5' => ['count' => 1, 'evidence' => '[R] Penetapan Program Manajemen Risiko Rumah Sakit oleh Direktur.'],
        'PMKP 11 / EP 6' => ['count' => 1, 'evidence' => '[D] Bukti FMEA proses berisiko tinggi setahun sekali.'],
    ],
];
